### ISSUE TITLE
Modify APC actions to trigger Argo cd pipeline

### ISSUE THREAD

**Issue by gamerslouis** [gamerslouis/cloudnative_apc_simulator#7]

**Comment by alan890104** [comment]
Please check [this branch](https://github.com/gamerslouis/cloudnative_apc_simulator/tree/feature/github_action)
Done.

**Comment by gamerslouis** [comment]
Add how to isntall arho cd to helm-charts repo readme

**Comment by alan890104** [comment]
https://github.com/gamerslouis/cloudnative_helm_charts/blob/main/readme.md
